language: java
jdk:  oraclejdk8

before_install:
  chmod +x mvnw

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 95ab884b-5ea3-4ec0-9a2c-d0fca3c8b7cd

notifications:
  email:
    - andriejsoft@gmail.com
