sudo:
  required

services:
  - docker

language: java
jdk:  oraclejdk8

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

before_install:
  chmod +x mvnw

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 95ab884b-5ea3-4ec0-9a2c-d0fca3c8b7cd
  - docker login -u $D_USER -p $D_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master"]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export NAME=andriejm/smlr
  - docker build -t $NAME:$COMMIT .
  - docker tag $NAME:$COMMIT $NAME:$TAG
  - docker push $NAME


notifications:
  email:
    - andriejsoft@gmail.com
